[package]
name = "libwmctl"
version = "0.0.3"
edition = "2018"
authors = ["phR0ze"]
license = "MIT OR Apache-2.0"
description = "Rust X11 automation"
repository = "https://github.com/phR0ze/wmctl"

[dependencies]
tracing = "0.1"
xcb = "0.10"
xcb-util = { version = "0.4", features = ["ewmh"] }